[package]
name = "QRcode"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
lazy_static = "1.5.0"
rayon = "1.10.0"
svg = "0.18.0"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
