[package]
name = "QRcode"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
rayon = "1.10.0"
tokio = { version = "1", features = ["full"] }

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
